# Imagen oficial de Prometheus
FROM prom/prometheus:v2.53.0

# Copiamos prometheus.yml desde la carpeta correcta
COPY monitoring/prometheus/prometheus.yml /etc/prometheus/prometheus.yml

EXPOSE 9090

ENTRYPOINT [ "prometheus" ]
CMD [ "--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus" ]